chore: limit service restart to 3
linuxdeepin/dde-session pull request #18
Opened 2023-04-23 03:03 UTC by justforlxz

Conditional judgment should be used to control the startup process

2023-04-24 09:47 UTC, zccrs requested changes

2023-04-24 09:47 UTC, zccrs commented on systemd/dde-session-initialized.target.wants/dde-session-daemon.target
> +Description=dde-session-daemon target
文件末尾都统一以空行结束，其它相同的地方就不评论了

2023-04-25 01:23 UTC, zccrs requested changes

2023-04-25 01:23 UTC, zccrs commented on systemd/dde-session-shutdown.target.d/dde-session-shutdown.conf
> +After=org.deepin.dde.Application1.Manager.service
空行结尾

2023-04-25 01:37 UTC, zccrs commented
/+1

2023-04-25 02:43 UTC, dengbo11 approved these changes

2023-04-25 03:21 UTC, zccrs approved these changes

2023-04-25 03:21 UTC, zccrs commented
以  @dengbo11 的 approved为赚

2023-04-25 03:30 UTC, merged