fix: no environment variable on wayland session
linuxdeepin/dde-session pull request #25
Opened 2023-05-09 09:02 UTC by justforlxz

set DE component after dde-session-pre.target

2023-05-10 11:57 UTC, zccrs requested changes

2023-05-10 11:57 UTC, zccrs commented on systemd/dde-session-initialized.target.wants/dde-session-daemon.target
> +Before=dde-session-initialized.target
以空行结尾

2023-05-10 11:57 UTC, zccrs commented on systemd/dde-session-manager.target
> -
怎么特意删掉了

2023-05-10 11:57 UTC, zccrs commented on systemd/dde-session-pre.target.wants/dde-display.service
>  After=dbus.socket
startdde还应该在kwin之后启动

2023-05-10 11:57 UTC, zccrs commented on systemd/dde-session.target
>  After=dde-session-initialized.target
这个还有用吗？

2023-05-10 11:57 UTC, zccrs commented on systemd/dde-session@wayland.service
> +After=dde-session-manager.service
这样它很可能是比startdde晚启动

2023-05-11 09:02 UTC, zccrs approved these changes

2023-05-11 09:30 UTC, dengbo11 approved these changes

2023-05-11 09:38 UTC, zccrs requested changes
还要确保 application-manager 在 startdde 之后启动，不然从dock、launcher中启动的程序没有缩放

2023-05-11 09:52 UTC, zccrs commented
> 还要确保 application-manager 在 startdde 之后启动，不然从dock、launcher中启动的程序没有缩放

AM 项目要单独改

2023-05-11 09:53 UTC, merged